import { GameState, RollHistoryEntry } from './types'

export const mockGameState: GameState = {
  players: [
    {
      id: '1',
      nickname: 'Alice',
      score: 245,
      hasBankedThisRound: false,
      isCurrentRoller: true,
      status: 'in',
    },
    {
      id: '2',
      nickname: 'Bob',
      score: 180,
      hasBankedThisRound: true,
      isCurrentRoller: false,
      status: 'banked',
    },
    {
      id: '3',
      nickname: 'Charlie',
      score: 320,
      hasBankedThisRound: false,
      isCurrentRoller: false,
      status: 'in',
    },
    {
      id: '4',
      nickname: 'Diana',
      score: 195,
      hasBankedThisRound: false,
      isCurrentRoller: false,
      status: 'in',
    },
  ],
  roundNumber: 3,
  totalRounds: 10,
  bankValue: 178,
  rollCountThisRound: 5,
  lastRoll: {
    die1: 4,
    die2: 3,
    sum: 7,
    wasDouble: false,
    effectType: 'add',
    effectText: '+7 to bank',
  },
  history: [
    {
      rollNumber: 1,
      playerNickname: 'Alice',
      die1: 5,
      die2: 5,
      result: '10',
      effect: 'Doubles! Bank +70',
    },
    {
      rollNumber: 2,
      playerNickname: 'Bob',
      die1: 3,
      die2: 4,
      result: '7',
      effect: '+7 to bank (special)',
    },
    {
      rollNumber: 3,
      playerNickname: 'Charlie',
      die1: 2,
      die2: 6,
      result: '8',
      effect: 'Bank doubled to 156',
    },
    {
      rollNumber: 4,
      playerNickname: 'Diana',
      die1: 6,
      die2: 5,
      result: '11',
      effect: '+11 to bank',
    },
    {
      rollNumber: 5,
      playerNickname: 'Alice',
      die1: 4,
      die2: 3,
      result: '7',
      effect: '+7 to bank',
    },
  ],
}
